title: Kristian Snyder
email: snyderkristian@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  DESCRIPTION!
baseurl: / # the subpath of your site, e.g. /blog
url: "http://kristiansnyder.com" # the base hostname & protocol for your site
twitter_username: kristian_snyder
github_username:  snyderks
spotify_profile: https://open.spotify.com/user/knsnyder96
my_name: Kristian

# Build settings
markdown: kramdown
theme: minima
exclude: [README.md, .gitignore, s3_website.yml, Gemfile, Gemfile.lock]

collections:
- jobs
- projects
