title: Kristian Snyder
email: contact@kristiansnyder.com
baseurl: / # the subpath of your site, e.g. /blog
twitter_username: kristian_snyder
github_username:  snyderks
spotify_profile: https://open.spotify.com/user/knsnyder96
my_name: Kristian
description: Software developer

plugins:
  - jekyll-sitemap
  - jekyll-feed

# Build settings
markdown: kramdown
theme: minima
exclude: [README.md, .gitignore, s3_website.yml, Gemfile, Gemfile.lock]
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter: rouge

  syntax_highlighter_opts:
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1


collections:
- jobs
- projects
- icons
